export interface FormInterface {
    state: string,
    postalState: string,
    title: string,
    surname: string,
    firstName: string,
    middleName: string,
    dateOfBirth: string,
    taxFileNumber: string,
    address: string,
    postCode: number,
    ownProperty: string,
    anotherProperty: string,
    bestInterest: string,
    loanFix: string,
    correctLoanStructure: string,
    freeLoanReview: string,
    postalAddress: string,
    postalPostCode: number,
    mobileNumber: string,
    email: string,
    customTitle: string,
    marketValue?: number,
    loan?: number
}
